using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class ModifierSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _modifier; // variables need to be private and they need to start with an underscore
}


/* ----- Begin Normal Autogenerated Code ----- */
public partial class ModifierSyncModel : RealtimeModel {
    public int modifier {
        get {
            return _modifierProperty.value;
        }
        set {
            if (_modifierProperty.value == value) return;
            _modifierProperty.value = value;
            InvalidateReliableLength();
            FireModifierDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ModifierSyncModel model, T value);
    public event PropertyChangedHandler<int> modifierDidChange;
    
    public enum PropertyID : uint {
        Modifier = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _modifierProperty;
    
    #endregion
    
    public ModifierSyncModel() : base(null) {
        _modifierProperty = new ReliableProperty<int>(1, _modifier);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _modifierProperty.UnsubscribeCallback();
    }
    
    private void FireModifierDidChange(int value) {
        try {
            modifierDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _modifierProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _modifierProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Modifier: {
                    changed = _modifierProperty.Read(stream, context);
                    if (changed) FireModifierDidChange(modifier);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _modifier = modifier;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
